apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.41
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: testdb
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: initdb-scripts
          configMap:
            name: mysql-init-scripts
