apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.44.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
      volumes:
        - name: prometheus-config
          hostPath:
            path: /backend/prometheus.yml
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc