apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql-deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 8080  # Porta que o serviço do Kubernetes usará para expor o Backend
      targetPort: 8080 # Porta em que o contêiner do meu aplicativo está escutando
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer # Disponível para fora do cluster
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  # Porta interna em que o Grafana está escutando
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090 
      targetPort: 9090
